version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - 7000:80
    volumes:
      - bundle:/usr/local/bundle
      - '.:/app'
    depends_on:
      - s3

  s3:
    extends:
      file: docker-compose.base.yml
      service: s3
    ports:
      - 9000:9000

volumes:
  bundle:
    driver: local