version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    volumes:
      - bundle:/usr/local/bundle
      - '.:/app'
    depends_on:
      - s3

  s3:
    extends:
      file: docker-compose.base.yml
      service: s3

volumes:
  bundle:
    driver: local