version: '2'
services:
  app:
    build: .
    ports:
      - 7000:80
    volumes:
      - bundle:/usr/local/bundle
      - '.:/app'
    environment:
      - S3_BUCKET=a-bucket
      - S3_REGION=a_region
      - S3_ACCESS_KEY_ID=an_access_key_id
      - S3_SECRET_ACCESS_KEY=a_secret_access_key
    command:
      bash -c "bundle exec rake development:up"

volumes:
  bundle:
    driver: local