#!/bin/bash

trap 'exit 1' SIGSEGV SIGTERM

shopt -s expand_aliases
alias docker-compose="docker-compose -f docker-compose.ci.yml"

docker-compose build
docker-compose up -d

docker-compose exec app bundle exec rake test:wait_for_environment
ok=$?

if [ $ok -eq 0 ]; then
  docker-compose exec app bundle exec rake test
  ok=$(($ok + $?))
fi

docker-compose down --rmi local --remove-orphans

exit $ok