#!/bin/bash

trap 'exit 1' SIGSEGV SIGTERM

shopt -s expand_aliases
alias docker-compose="docker-compose -f docker-compose.ci.yml"

docker-compose build
docker-compose up -d

##wait for application to be ready
sleep 5

docker-compose exec app bundle exec rake test

ok=$?

docker-compose down --rmi local --remove-orphans

exit $ok